### ISSUE TITLE
Reward of CryptoTradingEnv is not single step

### ISSUE THREAD

**Issue by QuantHao** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#37]
Hi, @praveen-palanisamy 

In CryptoTradingEnv, `reward` is computed based on ALL action steps, instead of current (single) action https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/31f8376095e635ab492bd853628417b9ef82694e/Chapter04/crypto_trading_env.py#L92

Do you think compute `reward` by `self.account_value - previous_account_value` might be more appropriate?

**Comment by QuantHao** [comment]
Same issue applies to Chapter 5.

**Comment by praveen-palanisamy** [comment]
The reward is intentionally set to be the profit/loss (`current_balance - opening_balance`) on the account controlled by the Agent so that the Agent learns a policy that maximizes the total return (profit).
The Agent is expected to learn the relationship between the series of actions (trades) it executes in an episode and the resulting reward (profit/loss).

Why do you think this is an issue (other than not being strictly Markovian)?
(Converting this to a discussion)
